BEGIN;

-- Ensure authentication-critical columns and defaults on users table.
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS location_id uuid;

ALTER TABLE users
  ALTER COLUMN username TYPE varchar(80),
  ALTER COLUMN username SET NOT NULL,
  ALTER COLUMN password_hash SET NOT NULL,
  ALTER COLUMN role TYPE user_role USING role::user_role,
  ALTER COLUMN role SET DEFAULT 'OPERATOR',
  ALTER COLUMN role SET NOT NULL,
  ALTER COLUMN is_active SET DEFAULT true,
  ALTER COLUMN is_active SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_users_location_id'
      AND conrelid = 'users'::regclass
  ) THEN
    ALTER TABLE users
      ADD CONSTRAINT fk_users_location_id
      FOREIGN KEY (location_id)
      REFERENCES locations (id);
  END IF;
END
$$;

-- Explicit unique index for username lookups in login flow.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_unique
  ON users (username);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'ck_users_branch_user_requires_location'
      AND conrelid = 'users'::regclass
  ) THEN
    ALTER TABLE users
      ADD CONSTRAINT ck_users_branch_user_requires_location
      CHECK (role = 'ADMIN' OR location_id IS NOT NULL)
      NOT VALID;
  END IF;
END
$$;

ALTER TABLE users
  VALIDATE CONSTRAINT ck_users_branch_user_requires_location;

COMMENT ON COLUMN users.location_id IS
  'Location assignment for user. NULL is allowed for central ADMIN; branch PHARMACIST/OPERATOR must have location.';
COMMENT ON INDEX idx_users_username_unique IS
  'Unique index used by username/password login.';

-- Guard seed assumptions: required branch locations must exist.
DO $$
DECLARE
  missing_codes text;
BEGIN
  SELECT string_agg(v.code, ', ' ORDER BY v.code)
  INTO missing_codes
  FROM (VALUES ('001'), ('003'), ('004')) AS v(code)
  LEFT JOIN locations l ON l.code = v.code
  WHERE l.id IS NULL;

  IF missing_codes IS NOT NULL THEN
    RAISE EXCEPTION 'Missing required branch locations for auth seed: %', missing_codes;
  END IF;
END
$$;

-- Seed login users.
-- Password for all seed users: changeme (bcrypt cost 10)
-- Hash generated by bcrypt: $2b$10$pJaKRMH58xvj.CnovUqdD.xrdbBP.NwoJGaswYoPkyFlom0h2i/7W

INSERT INTO users (
  username,
  password_hash,
  full_name,
  role,
  location_id,
  is_active,
  updated_at
)
VALUES (
  'admin000',
  '$2b$10$pJaKRMH58xvj.CnovUqdD.xrdbBP.NwoJGaswYoPkyFlom0h2i/7W',
  'Admin 000',
  'ADMIN',
  NULL,
  true,
  now()
)
ON CONFLICT (username) DO UPDATE
SET
  password_hash = EXCLUDED.password_hash,
  full_name = EXCLUDED.full_name,
  role = EXCLUDED.role,
  location_id = NULL,
  is_active = EXCLUDED.is_active,
  updated_at = now();

WITH seed_branch_users AS (
  SELECT *
  FROM (
    VALUES
      ('branch001', 'Pharmacist Branch 001', '001'),
      ('branch003', 'Pharmacist Branch 003', '003'),
      ('branch004', 'Pharmacist Branch 004', '004')
  ) AS x(username, full_name, location_code)
),
location_map AS (
  SELECT code, id
  FROM locations
  WHERE code IN ('001', '003', '004')
)
INSERT INTO users (
  username,
  password_hash,
  full_name,
  role,
  location_id,
  is_active,
  updated_at
)
SELECT
  s.username,
  '$2b$10$pJaKRMH58xvj.CnovUqdD.xrdbBP.NwoJGaswYoPkyFlom0h2i/7W',
  s.full_name,
  'PHARMACIST',
  l.id,
  true,
  now()
FROM seed_branch_users s
JOIN location_map l
  ON l.code = s.location_code
ON CONFLICT (username) DO UPDATE
SET
  password_hash = EXCLUDED.password_hash,
  full_name = EXCLUDED.full_name,
  role = EXCLUDED.role,
  location_id = EXCLUDED.location_id,
  is_active = EXCLUDED.is_active,
  updated_at = now();

COMMIT;
