BEGIN;

-- Ensure branch 005 exists before assigning staff005.
INSERT INTO locations (code, name, location_type, is_active)
VALUES ('005', 'Branch 005', 'BRANCH', true)
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  location_type = EXCLUDED.location_type,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- Password for all seed logins below: 123123 (bcrypt cost 10)
-- Hash generated by bcrypt: $2b$10$vKoTGMybor3nNrBgxVrr3.ZaBP9TuRopfTq3uHnagszqVggE/qPsu

DO $$
DECLARE
  v_password_hash constant text := '$2b$10$vKoTGMybor3nNrBgxVrr3.ZaBP9TuRopfTq3uHnagszqVggE/qPsu';
  v_old_user_id uuid;
  v_target_user_id uuid;
  v_location_id uuid;
  rec record;
BEGIN
  SELECT id INTO v_old_user_id
  FROM users
  WHERE username = 'admin000';

  SELECT id INTO v_target_user_id
  FROM users
  WHERE username = 'admin';

  IF v_old_user_id IS NOT NULL THEN
    IF v_target_user_id IS NOT NULL AND v_target_user_id <> v_old_user_id THEN
      RAISE EXCEPTION 'Cannot rename admin000 to admin because username admin already belongs to another user (%).', v_target_user_id;
    END IF;

    UPDATE users
    SET
      username = 'admin',
      password_hash = v_password_hash,
      full_name = 'Admin',
      role = 'ADMIN',
      location_id = NULL,
      is_active = true,
      updated_at = now()
    WHERE id = v_old_user_id;
  ELSIF v_target_user_id IS NOT NULL THEN
    UPDATE users
    SET
      password_hash = v_password_hash,
      full_name = 'Admin',
      role = 'ADMIN',
      location_id = NULL,
      is_active = true,
      updated_at = now()
    WHERE id = v_target_user_id;
  ELSE
    INSERT INTO users (
      username,
      password_hash,
      full_name,
      role,
      location_id,
      is_active,
      updated_at
    )
    VALUES (
      'admin',
      v_password_hash,
      'Admin',
      'ADMIN',
      NULL,
      true,
      now()
    );
  END IF;

  FOR rec IN
    SELECT *
    FROM (
      VALUES
        ('branch001', 'staff001', 'Staff Branch 001', '001'),
        ('branch003', 'staff003', 'Staff Branch 003', '003'),
        ('branch004', 'staff004', 'Staff Branch 004', '004'),
        (NULL, 'staff005', 'Staff Branch 005', '005')
    ) AS seed(old_username, new_username, full_name, location_code)
  LOOP
    SELECT id INTO v_location_id
    FROM locations
    WHERE code = rec.location_code;

    IF v_location_id IS NULL THEN
      RAISE EXCEPTION 'Missing location for branch code %.', rec.location_code;
    END IF;

    v_old_user_id := NULL;
    v_target_user_id := NULL;

    IF rec.old_username IS NOT NULL THEN
      SELECT id INTO v_old_user_id
      FROM users
      WHERE username = rec.old_username;
    END IF;

    SELECT id INTO v_target_user_id
    FROM users
    WHERE username = rec.new_username;

    IF v_old_user_id IS NOT NULL THEN
      IF v_target_user_id IS NOT NULL AND v_target_user_id <> v_old_user_id THEN
        RAISE EXCEPTION 'Cannot rename % to % because target username already belongs to another user (%).', rec.old_username, rec.new_username, v_target_user_id;
      END IF;

      UPDATE users
      SET
        username = rec.new_username,
        password_hash = v_password_hash,
        full_name = rec.full_name,
        role = 'PHARMACIST',
        location_id = v_location_id,
        is_active = true,
        updated_at = now()
      WHERE id = v_old_user_id;
    ELSIF v_target_user_id IS NOT NULL THEN
      UPDATE users
      SET
        password_hash = v_password_hash,
        full_name = rec.full_name,
        role = 'PHARMACIST',
        location_id = v_location_id,
        is_active = true,
        updated_at = now()
      WHERE id = v_target_user_id;
    ELSE
      INSERT INTO users (
        username,
        password_hash,
        full_name,
        role,
        location_id,
        is_active,
        updated_at
      )
      VALUES (
        rec.new_username,
        v_password_hash,
        rec.full_name,
        'PHARMACIST',
        v_location_id,
        true,
        now()
      );
    END IF;
  END LOOP;
END
$$;

COMMIT;
